name: "Heartbeat"

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'

permissions: write-all

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
    - name: Heartbeat
      shell: bash
      run: |
        response=$(curl -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36' -L --max-redirs 20 --connect-timeout 300 -m 900 -Y 0 -y 300 -w '%{http_code}' -s -o /dev/null '${{ secrets.WORKFLOW_TOKEN }}')
        status="$?"
        if [[ "$status" -ne 0 ]] ; then
          echo "CURL $status"
          echo "::error ::CURL $status"
          exit 1
        fi
        echo "HTTP $response"
        if [[ "$response" -ne 200 ]] ; then
          echo "::error ::HTTP $response"
          exit 1
        fi
        exit 0
